//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSeal.Core.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrgService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrgService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalSeal.Core.Resources.Services.OrgService", typeof(OrgService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the currently used organization. Switch to another organization and try again.
        /// </summary>
        internal static string DeleteCurrent {
            get {
                return ResourceManager.GetString("DeleteCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete your last personal organization.
        /// </summary>
        internal static string DeleteLast {
            get {
                return ResourceManager.GetString("DeleteLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to delete organization {0}.
        /// </summary>
        internal static string DeleteNoPermission {
            get {
                return ResourceManager.GetString("DeleteNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot leave an organization that you own.
        /// </summary>
        internal static string KickOwned {
            get {
                return ResourceManager.GetString("KickOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot kick the owner of the organzation.
        /// </summary>
        internal static string KickOwner {
            get {
                return ResourceManager.GetString("KickOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot leave currently used organization. Switch to another organization and try again.
        /// </summary>
        internal static string LeaveCurrent {
            get {
                return ResourceManager.GetString("LeaveCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action.
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization not found.
        /// </summary>
        internal static string OrgNotFound {
            get {
                return ResourceManager.GetString("OrgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party already exists.
        /// </summary>
        internal static string PartyExists {
            get {
                return ResourceManager.GetString("PartyExists", resourceCulture);
            }
        }
    }
}
